require 'rails_helper'

describe 'proposals/_description' do

  before(:each) do
    @proposal = mock_model(Proposal, :description => "A description", :description? => true)
    allow(view).to receive(:proposal).and_return(@proposal)
  end

  it "escapes HTML in the description" do
    allow(@proposal).to receive(:description).and_return('test123"\'<img src=xyz onerror=alert(1) foo=>')
    render
    expect(rendered).not_to have_selector(:img)
  end

  it "allows HTML that has been generated by Markdown to pass through" do
    render
    expect(rendered).not_to match(/&lt;p/)
  end
end
