#!/usr/bin/env ruby

ENV_PATH  = File.expand_path('../../config/environment',  __FILE__)
BOOT_PATH = File.expand_path('../../config/boot',  __FILE__)
APP_PATH  = File.expand_path('../../config/application',  __FILE__)

require ENV_PATH
require 'delayed/command'

Delayed::Command.new(ARGV).daemonize
